config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'parking_spaces#index'
  get 'parking_spaces/free_parking_space', to: 'parking_spaces#free_parking_space'
  
  get 'parking_spaces/unpark_form', to: 'parking_spaces#unpark_form'
  put 'parking_spaces/unpark', to: 'parking_spaces#unpark'
  
  get 'parking_spaces/find_vehical_form', to: 'parking_spaces#find_vehical_form'
  get 'parking_spaces/find_vehical', to: 'parking_spaces#find_vehical'
  
  resources :parking_spaces do 
    collection do
      get :render_available_space_type
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike_space.rb
class BikeSpace < ParkingSpace
end

app/models/car_space.rb
class CarSpace < ParkingSpace

end

app/models/parking_space.rb
class ParkingSpace < ApplicationRecord
  before_create :add_spot_number
  
  scope :parked,-> { where.not(vehicle_number: "", parking_number: "")}
  scope :available_parking_space,-> { where(vehicle_number: "", parking_number: "")}

  def vehicle_type
    self.class.name.underscore.humanize.split(" ").first
  end

  private
  
  def add_spot_number
    self.spot_number = "#{(self.class.name)}_#{(self.class&.last&.id.to_i + 1)}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parking_spaces_controller.rb
class ParkingSpacesController < ApplicationController
  before_action :find_my_vehical, only: [:find_vehical, :unpark]

  def index
    @parking_spaces = ParkingSpace.all.order(spot_number: :desc).paginate(page: params[:page], per_page: 10)
  end

  def free_parking_space
    @parking_spaces = ParkingSpace.available_parking_space.order(spot_number: :desc).paginate(page: params[:page], per_page: 10)
  end

  def new
    @parking_space = ParkingSpace.new()
  end

  def create
    @parking_space = ParkingSpace.find_by(spot_number: params[:spot_number])
    if @parking_space.update(parking_params)
      flash.now[:success] = "Vehicle Parked"
      redirect_to parking_spaces_path
    else
      render :new
    end
  end

  def unpark_form
  end

  def unpark
    respond_to do |format|
      if @parking_space.present?
        @parking_space.update(parking_number: "", vehicle_number: "")
        format.html { redirect_to parking_spaces_path, notice: 'Post was successfully updated.' }
      else
        format.html { render parking_spaces_unpark_form_path, flash: { notice: 'Could not find the vehicle.' }}
      end
    end     
  end
  
  def find_vehical_form
  end

  def find_vehical
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def render_available_space_type
    @space = ParkingSpace.available_parking_space.where(type: "#{params[:type]}Space").pluck(:id, :spot_number)
    render json: {
      data: @space.map { |key, val|
        [ text: val, value: key ]
      }
    }
  end

  def set_space
    @parking_space = ParkingSpace.find_by(id: params[:id])
  end

  def parking_params
    params.require(:parking_space).permit( :parking_number, :vehicle_number )
  end

  def find_my_vehical
    action = params[:action].to_sym
    parking_number = params[action][:parking_number]
    vehicle_number = params[action][:vehicle_number]
    @parking_space = ParkingSpace.parked.where('parking_number=? OR vehicle_number=?', parking_number , vehicle_number).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_paginate data
    will_paginate data, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'my-4 justify-content-between'
  end
end

app/views/layouts/_flash_with_toastr.slim
- flash.keys.each do |key|
  - toastr_key = TOASTR_KEYS[key]
  javascript:
    $(function() {
      toastr["#{toastr_key}"]("#{flash[key]}");
    });

app/views/layouts/_navigation.slim
nav.navbar.navbar-expand-lg.navbar-light.fixed-top style="background-color: #6a788e;"
  .container
    = link_to 'Home', parking_spaces_path, class: 'navbar-brand text-white'

    button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
      span.navbar-toggler-icon

    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        li.nav-item.active
          = link_to 'Free Space', parking_spaces_free_parking_space_path, class: 'nav-link text-white'
        li.nav-item.active
          = link_to 'Park', new_parking_space_path, class: 'nav-link text-white'
        li.nav-item.active
          = link_to 'UnPark', parking_spaces_unpark_form_path, class: 'nav-link text-white'
        li.nav-item.active
          = link_to 'Find vehical', parking_spaces_find_vehical_form_path, class: 'nav-link text-white'

app/views/layouts/application.slim
head
  meta charset="utf-8"
  meta http="equiv=X-UA-Compatible" content="IE=edge"
  meta content="width=device-width, initial-scale=1.0" name="viewport"
  title = content_for?(:title) ? yield(:title) : 'Parking Lot'

  = stylesheet_link_tag     'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag  'application', 'data-turbolinks-track': 'reload'
  = stylesheet_link_tag     "page_specific/#{controller_name}"
  = javascript_include_tag  "page_specific/#{controller_name}"
  = csrf_meta_tags
  = csp_meta_tag
/ body
/   = render 'layouts/navigation'
/   .row
/     .col-12.mt-3
/       .container.my-5
/         = yield
/ footer




body
  .row
    .col-12.mt-3
      .container.my-5
        .app-header = render 'layouts/navigation'
        
          = render 'layouts/flash_with_toastr'

        = yield

footer

app/views/parking_spaces/_find_vehical_form.slim
.row.mb-3
  .col-12
    = f.input :parking_number, label: 'Parking ID *', input_html: {class: 'form-control' }
.row.mb-3
  .col-12
    = f.input :vehicle_number, label: 'Vehicle Number', input_html: { class: 'form-control mb-3 ', rows: 5 }
.row.mb-3
  .col-12
    = f.button :submit, 'Submit', class: 'btn btn-success mr-2'

app/views/parking_spaces/_index.slim
.static_wrapper
  .card.shadow
    .card-body
      .table-responsive
        table.table.table-bordered
          thead
            tr
              th Spot Number
              th Type
              th Vehicle Number
              th Vehicle Reference Id
          tbody
            - parking_spaces.each do |parking_space|
              tr
                td = parking_space.spot_number
                td = parking_space.vehicle_type
                - if parking_space.vehicle_number.present? 
                  td = parking_space.vehicle_number
                  td = parking_space.parking_number
                - else 
                  td.strong FREE SPACE
                  td.string FREE SPACE
- if parking_spaces.present?
  .row
    .col-12
      .float-left.my-4.blog-page-info.pad7tp.blog-text-color.ml-2 = page_entries_info( parking_spaces, model: '' )
      .float-right.mr-2 = bootstrap_paginate parking_spaces

app/views/parking_spaces/_vehical_information.slim
-if parking_space.present?
  .static_wrapper
    .card.shadow
      .card-body
        .table-responsive
          table.table.table-bordered
            thead
              tr
                th Spot Number
                th Type
                th Vehicle Number
                th Vehicle Reference Id
            tbody
              tr
                td = parking_space.spot_number
                td = parking_space.vehicle_type
                td = parking_space.vehicle_number
                td = parking_space.parking_number
-else 
  .alert.alert-info.text-center.fn-14 Vehical Not Fount, No data to show

app/views/parking_spaces/find_vehical.js.erb
$('#vehical_information').html('');
$('#vehical_information').prepend('<%= j render "parking_spaces/vehical_information", parking_space: @parking_space %>');

app/views/parking_spaces/find_vehical_form.slim
.row
  .col-sm-12.col-md-8.offset-md-2
    .card.mt-3.mb-5.
      .card-header = "#{action_name&.titleize}"
      .card-body
        = simple_form_for :find_vehical, url: { controller: 'parking_spaces', action: 'find_vehical' }, html: { method: :get, class: 'm-0 unpark' }, remote: true do |f|
          = render 'parking_spaces/find_vehical_form', f: f
        .row
          .col-12#vehical_information

app/views/parking_spaces/free_parking_space.slim
= render "parking_spaces/index", parking_spaces: @parking_spaces

app/views/parking_spaces/index.slim
= render "parking_spaces/index", parking_spaces: @parking_spaces

app/views/parking_spaces/new.slim
.row
  .col-sm-12.col-md-8.offset-md-2
    .card.mt-3.mb-5.
      .card-header = "#{action_name&.titleize}"
      .card-body
        = simple_form_for @parking_space, html: { class: 'm-0 park ' } do |f|
          .row.mb-3
            .col-12
              = f.input :parking_number, label: 'Parking ID *', readonly: true, input_html: {class: 'form-control', value: "VEHICLE#{DateTime.now.strftime('%d%m%Y%H%M%S')}" }

          .row.mb-3
            .col-12
              = f.input :vehicle_number, label: 'Vehicle Number *', input_html: { class: 'form-control mb-3 ', rows: 5 }

          .row.mb-3
            .col-12              
              = label_tag :type, 'Vehicle Type *'
              = select_tag :type, options_for_select(['Car', 'Bike']), id: 'type_select', class: 'selectize', include_blank: true, name: 'parking_space[vehicle_type]'
          
          .row.mb-3
            .col-12              
              = label_tag :spot_number, 'Spot Number *'
              = select_tag :parking_space_id, options_for_select([]), id: 'spot_select', class: 'selectize', include_blank: true, name: 'parking_space[spot_number]'
          .row.mb-3
            .col-12
              = f.button :submit, 'Submit', class: 'btn btn-success mr-2'

app/views/parking_spaces/unpark_form.slim
.row
  .col-sm-12.col-md-8.offset-md-2
    .card.mt-3.mb-5.
      .card-header = "#{action_name&.titleize}"
      .card-body
        = simple_form_for :unpark, url: { controller: 'parking_spaces', action: 'unpark' }, html: { method: :put, class: 'm-0 unpark' } do |f|
          = render 'parking_spaces/find_vehical_form', f: f